#-> ~/.config/miteclock/config.toml

account = "retresco"
menu_keys="arstneio"

[shortcuts]
# Services
k= "Kommunikation"
e= "Entwicklung"
q= {"pattern"= "QA", "match"= "strict"}
d="Dokumentation"
z= "Entwickler-Konzeption"
r = "Research"
# Projects
c= "CoreEngine"
n= "NLG-Plattform"
i= "Intern_"
v= "Variant Suggestions"
# Current Westermann project
w="M6_Transformationsregeln"
# Full activity shortcuts
meet = ["i", "k"]
daily= ["meet", "daily stand-up"]
amly= ["meet", "morning stand-up"]
pmly= ["meet", "afternoon stand-up"]
weekly= ["meet", "weekly team meeting"]
retro= ["meet", "retrospective"]
est= ["meet", "estimation meeting"]
prepest= ["meet", "estimate tickets before meeting"]
sotu= ["meet", "State Of The Union; aka company weekly"]
devb=["meet", "dev breakfast"]
sprintrev=["w", "k", "sprint review"]
mlguild=["i", "r", "machine learning guild"]
