#-> ~/.config/miteclock/config.toml

account = "retresco"
menu_keys="arstneio"

[shortcuts]
# Services
k= "Kommunikation"
e= "Entwicklung"
q= {"pattern"= "QA", "match"= "strict"}
d="Dokumentation"
z= "Entwickler-Konzeption"
r = "Research"
# This is separate from the "Intern" project.
is = "RTR intern"
it = "IT-Administration"
# Projects
c= "CoreEngine"
n="NLG-Plattform"
i= "Intern_"
v= "Variant Suggestions"
g="Guilds"
# Current Westermann project: QA and Hardening
w="M8_Productive"
# Full activity shortcuts
meet = ["i", "k"]
tio = ["n", "e"]
guild_work = ["g", "e"]
org = ["i", "is", "task/email review"]
daily= ["meet", "daily stand-up"]
amly= ["meet", "morning stand-up"]
pmly= ["meet", "afternoon stand-up"]
weekly= ["meet", "weekly team meeting"]
retro= ["meet", "retrospective"]
est= ["meet", "estimation meeting"]
prepest= ["meet", "estimate tickets before meeting"]
sotu= ["meet", "State Of The Union; aka company weekly"]
devb=["meet", "dev breakfast"]
sprintrev=["w", "k", "sprint review"]
mlguild=["guild_work", "machine learning guild"]
scguild=["guild_work", "software craftsmanship guild"]
hack=["i", "e", "hackathon"]
tiodemo = ["meet", "textengine.io product demo"]
ccc=["meet", 'core clean code']
jf = ['meet', 'Jour Fixe with Wolfgang about improving delivery']
