* TODO pyenv
* TODO pipx
* my scripts
  ~pyudev~ package is needed by the ~extmonitor~ script, honestly consider turning it into a simple package so that you can install it in a sandbox with all its dependencies using pipx.
* Shell scripts
  Need to install https://github.com/koalaman/shellcheck for shell scripts layer to work.
* packages
  This command should just install the packages that are needed from the very beginning
  #+begin_src sh
    sudo dnf install -y \
         ShellCheck \
         acpi \
         arandr \
         calibre \
         dunst \
         git \
         htop \
         i3 \
         levien-inconsolata-fonts \
         linux-libertine-biolinum-fonts \
         network-manager-applet \
         redshift \
         ripgrep \
         rofi \
         xrandr
  #+end_src
* Calibre
  Can be installed manually or with snap (not recommended by devs).

  Copy the backed up books and point calibre to them.
* dropbox
  gotta install the client manually, then hook it up to startup.
* coding
  Place ~docsets~ folder in the ~~/code~ folder.
* spacemacs
  clone spacemacs folder into ~.emacs.d~.
  the linker script will take care of the rest
* Battery Status
  add this to your crontab:
  #+begin_src
*/3 * * * * $HOME/code/configs/battery_status_check.sh
  #+end_src
* i3
** py3status
   #+begin_src sh
     pipx install py3status && pipx inject py3status pytz tzlocal
   #+end_src
* Mouse setup
  Copy this to ~/etc/X11/xorg.conf.d/10-libinput.conf~:
  #+begin_src
Section "InputClass"
  Identifier   "Marble Mouse"
  MatchProduct "Logitech USB Trackball"
  Driver       "libinput"
  Option       "ScrollMethod"    "button"
  Option       "ScrollButton"    "8"
  Option       "MiddleEmulation" "true"
EndSection
  #+end_src
