#!/usr/bin/env bash
# -*- mode:shell-script; -*-
EMAIL="ilia.kurenkov@retresco.de"
UNAME="Ilia Kurenkov"

set -eo pipefail

cd ~/code
git clone $1
echo "Moving into repo"
cd $(basename $1 .git)
echo "Setting RTR email"
git config --local user.email $EMAIL
git config --local user.name $UNAME
