#!/bin/bash
set -e

displays=`xrandr | awk '$2=="connected" { print $1 }'`
ndisplays=$(echo "$displays" | wc -l)

if [ $ndisplays -eq 2 ]; then
    # handle dual display
    read internal external <<<$(echo $displays)
    echo $internal
    action=`printf 'connect\ndisconnect' | rofi -dmenu -i -p "Detected an external display "$external". Choose action:"`
    echo "$action"
    if [ "$action" = "disconnect" ]; then
        xrandr --output "$internal" --scale 1.0x1.0 \
               --output "$external" --off
    else
        direction=`printf 'nleft\right' | rofi -dmenu -i -p "Which side to place external on:"`
        rotation=`printf 'left\nright\nnormal' | rofi -dmenu -i -p "Rotation:"`
        xrandr --output "$internal" --auto --scale 1.0x1.0 \
               --output "$external" --auto --scale 1.0x1.0 \
               --"$direction"-of "$internal" --rotate "$rotation" --primary
        # For now this is copy/pasted here and in i3config, would be nice to have
        # one place to keep this logic.
        feh --bg-max --randomize ~/Pictures/wallpapers/* &
    fi
elif [ $ndisplays -eq 1 ]; then
    notify-send "Only found one display, resetting it."
    xrandr --output "$displays" --auto --scale 1.0x1.0 --primary
    exit 0
else
    notify-send "Found more than 2 displays, I don't know what to do."
    exit 0
fi
