#!/usr/bin/env bash
#-> ~/bin/{name}

set -eo pipefail

if [ "$(hostname)" = "work" ]; then
    xrandr --output eDP --mode 1280x720
    selectdisplay reconnect left left
    # have tried "connect" here too, no luck
    dropbox start
    startvpn
else
    selectdisplay
    dropboxd &
fi
