#!/usr/bin/env bash

echo "mesos-gate VPN"
ovpn_pid=$(pgrep openvpn)
if [ $? -eq 0 -a -n "${ovpn_pid}" ]; then
    echo "Restarting openvpn[${ovpn_pid}]..."
    sudo kill ${ovpn_pid}
fi
sudo openvpn \
     --daemon \
     --config $HOME/vpn/ikurenkov.ovpn \
     --tls-auth ~/vpn/ta.key \
     --auth-user-pass $HOME/vpn/username
