#!/usr/bin/env bash
#-> ~/bin/{name}

set -eo pipefail

if [ "$(hostname)" != "work" ]; then
    notify-send "This is not work, no need for VPN!"
    exit 0
fi

credentials_file="${HOME}"/.rtr-credentials
if [ -f "${credentials_file}" ]; then
    passwd=$(sed "2q;d" "${credentials_file}" | tr -d "\n")
else
    passwd=$(rofi -dmenu -password -p "sudo password for rtr vpn")
fi
set +e
ovpn_pid=$(pgrep openvpn)
set -e
if [ -n "${ovpn_pid}" ]; then
    notify-send "Stopping existing openvpn[${ovpn_pid}]..."
    echo "${passwd}" | sudo -S kill "${ovpn_pid}"
fi
notify-send "Starting openvpn"
echo "${passwd}" | sudo -S openvpn \
                    --daemon \
                    --config "${HOME}/vpn/ikurenkov.ovpn" \
                    --tls-auth "${HOME}/vpn/ta.key" \
                    --auth-user-pass "${credentials_file}"
